# docker-compose.yml
# Version: 1.3.6 - 2025-07-01 08:42 UTC
# Changelog:
# - updated Caddyfile location

services:
  reverse-proxy:
    image: caddy:latest
    container_name: iot-reverse-proxy
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./caddy_config/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./ui-versions:/var/www/ui-versions:ro
    env_file:
      - .env
    networks:
      - sensemy_network
    depends_on:
      - device-manager
      - ingest-service
      - analytics-processor
    restart: unless-stopped

  analytics-processor:
    build:
      context: ./analytics-processor-v2
      dockerfile: ../analytics-processor-v2/Dockerfile
    image: analytics-processor:latest
    ports:
      - "${ANALYTICS_SERVICE_PORT}:${ANALYTICS_SERVICE_PORT}"
    env_file: .env
    environment:
      ANALYTICS_SERVICE_PORT: ${ANALYTICS_SERVICE_PORT}
      ANALYTICS_DB_HOST: ${ANALYTICS_DB_HOST}
      ANALYTICS_DB_PORT: ${ANALYTICS_DB_PORT}
      ANALYTICS_DB_USER: ${ANALYTICS_DB_USER}
      ANALYTICS_DB_PASSWORD: ${ANALYTICS_DB_PASSWORD}
      ANALYTICS_DB_NAME: ${ANALYTICS_DB_NAME}
      INGEST_DB_HOST: ${INGEST_DB_HOST}
      INGEST_DB_PORT: ${INGEST_DB_PORT}
      INGEST_DB_USER: ${INGEST_DB_USER}
      INGEST_DB_PASSWORD: ${INGEST_DB_PASSWORD}
      INGEST_DB_NAME: ${INGEST_DB_NAME}
      DEVICE_DB_HOST: ${DEVICE_DB_HOST}
      DEVICE_DB_PORT: ${DEVICE_DB_PORT}
      DEVICE_DB_USER: ${DEVICE_DB_USER}
      DEVICE_DB_PASSWORD: ${DEVICE_DB_PASSWORD}
      DEVICE_DB_NAME: ${DEVICE_DB_NAME}
      LOG_LEVEL: ${LOG_LEVEL}
      TZ: ${TIMEZONE}
    depends_on:
      - analytics-database
      - ingest-database
      - device-database
    networks:
      - sensemy_network
    restart: unless-stopped

  device-manager:
    build:
      context: ./device-manager
    container_name: device-manager
    ports:
      - "${DEVICE_MANAGER_SERVICE_PORT}:${DEVICE_MANAGER_SERVICE_PORT}"
    env_file: .env
    environment:
      DATABASE_URL: "postgresql+psycopg2://${DEVICE_DB_USER}:${DEVICE_DB_PASSWORD}@${DEVICE_DB_HOST}:${DEVICE_DB_PORT}/${DEVICE_DB_NAME}"
      ANALYTICS_PROCESSOR_URL: "${ANALYTICS_URL}"
      ANALYTICS_ENABLED: "true"
      LOG_LEVEL: ${LOG_LEVEL}
      TZ: ${TIMEZONE}
    depends_on:
      - device-database
    networks:
      - sensemy_network
    restart: unless-stopped

  ingest-service:
    build:
      context: ./ingest-server
    container_name: ingest-service
    ports:
      - "${INGEST_SERVICE_PORT}:${INGEST_SERVICE_PORT}"
    env_file: .env
    environment:
      DATABASE_URL: "postgresql://${INGEST_DB_USER}:${INGEST_DB_PASSWORD}@${INGEST_DB_HOST}:${INGEST_DB_PORT}/${INGEST_DB_NAME}"
      POSTGRES_HOST: ${INGEST_DB_HOST}
      POSTGRES_DB: ${INGEST_DB_NAME}
      POSTGRES_USER: ${INGEST_DB_USER}
      POSTGRES_PASSWORD: ${INGEST_DB_PASSWORD}
      DEVICE_MANAGER_URL: "http://device-manager:${DEVICE_MANAGER_SERVICE_PORT}/process-uplink"
      LOG_LEVEL: ${LOG_LEVEL}
      TZ: ${TIMEZONE}
    depends_on:
      - ingest-database
    networks:
      - sensemy_network
    restart: unless-stopped

  analytics-database:
    image: postgres:15
    container_name: analytics-database
    env_file: .env
    environment:
      POSTGRES_DB: ${ANALYTICS_DB_NAME}
      POSTGRES_USER: ${ANALYTICS_DB_USER}
      POSTGRES_PASSWORD: ${ANALYTICS_DB_PASSWORD}
      TZ: ${TIMEZONE}
    ports:
      - "${ANALYTICS_DB_PORT}:5432"
    volumes:
      - analytics_db_data:/var/lib/postgresql/data
    networks:
      - sensemy_network
    restart: unless-stopped

  ingest-database:
    image: postgres:15
    container_name: ingest-database
    env_file: .env
    environment:
      POSTGRES_DB: ${INGEST_DB_NAME}
      POSTGRES_USER: ${INGEST_DB_USER}
      POSTGRES_PASSWORD: ${INGEST_DB_PASSWORD}
      TZ: ${TIMEZONE}
    ports:
      - "${INGEST_DB_PORT}:5432"
    volumes:
      - ingest_db_data:/var/lib/postgresql/data
    networks:
      - sensemy_network
    restart: unless-stopped

  device-database:
    image: postgres:15
    container_name: device-database
    env_file: .env
    environment:
      POSTGRES_DB: ${DEVICE_DB_NAME}
      POSTGRES_USER: ${DEVICE_DB_USER}
      POSTGRES_PASSWORD: ${DEVICE_DB_PASSWORD}
      TZ: ${TIMEZONE}
    ports:
      - "${DEVICE_DB_PORT}:5432"
    volumes:
      - device_db_data:/var/lib/postgresql/data
    networks:
      - sensemy_network
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: adminer-ui
    ports:
      - "${ADMINER_PORT}:8080"
    restart: unless-stopped
    networks:
      - sensemy_network

volumes:
  analytics_db_data:
  ingest_db_data:
  device_db_data:
  caddy_data:
  caddy_config:

networks:
  sensemy_network:
    name: sensemy_network
    driver: bridge
